keep track of disk usage when partitioning

diff --git a/functions/00-install b/functions/00-install
--- a/functions/00-install
+++ b/functions/00-install
@@ -95,6 +95,7 @@ function ask_partition_scheme {
 }
 
 BOOTMODE=
+MAKE_EFI_PARTITION=yes
 function ask_bootmode {
   show_header "Boot system:"
   if [ -e /sys/firmware/efi ]; then
@@ -124,35 +125,214 @@ function ask_bootmode {
   else
     show_info "EFI support not detected. Defaulting to GRUB."
     BOOTMODE="GRUB"
+    result="$(ask_question "Create EFI partition? (y/N)")"
+    if ! [[ "${result}" =~ ^[Yy]$|[Yy][Ee][Ss] ]]; then
+      MAKE_EFI_PARTITION=no
+    fi
   fi
+}
+
+function sanitize_size_input {
+  local value
+  local suffix
+  value="$(echo "${1}" | sed -n 's/^\([0-9\.]\+\)\ *[A-Za-z]*/\1/p')"
+  suffix="$(echo "${1}" | sed -n 's/^[0-9\.]\+\ *\([A-Za-z]\+\)/\1/p')"
+
+  # if using base 10 units
+  if [[ "${1}" = "fill" ]]; then
+    value="${1}"
+
+  elif [[ "${suffix}" =~ ^[Pp]etabyte|^[Pp][Bb]s?$ ]]; then
+    value="$(echo "${value} * 1000^5 / 1024" | bc -l)"
+    value="${value%.*}k"
+  elif [[ "${suffix}" =~ ^[Tt]erabyte|^[Tt][Bb]s?$ ]]; then
+    value="$(echo "${value} * 1000^4 / 1024" | bc -l)"
+    value="${value%.*}k"
+  elif [[ "${suffix}" =~ ^[Gg]igabyte|^[Gg][Bb]s?$ ]]; then
+    value="$(echo "${value} * 1000^3 / 1024" | bc -l)"
+    value="${value%.*}k"
+  elif [[ "${suffix}" =~ ^[Mm]egabyte|^[Mm][Bb]s?$ ]]; then
+    value="$(echo "${value} * 1000^2 / 1024" | bc -l)"
+    value="${value%.*}k"
+  elif [[ "${suffix}" =~ ^[Kk]ilobyte|^[Kk][Bb]s?$ ]]; then
+    value="$(echo "${value} * 1000^1 / 1024" | bc -l)"
+    value="${value%.*}k"
+
+  elif [[ "${suffix}" =~ ^[Pp]ebibyte|^[Pp]i[Bb]s?$|^[Pp]$ ]]; then
+    value="$(echo "${value} * 1024^4" | bc -l)"
+    value="${value%.*}k"
+  elif [[ "${suffix}" =~ ^[Tt]ebibyte|^[Tt]i[Bb]s?$|^[Tt]$ ]]; then
+    value="$(echo "${value} * 1024^3" | bc -l)"
+    value="${value%.*}k"
+  elif [[ "${suffix}" =~ ^[Gg]ibibyte|^[Gg]i[Bb]s?$|^[Gg]$ ]]; then
+    value="$(echo "${value} * 1024^2" | bc -l)"
+    value="${value%.*}k"
+  elif [[ "${suffix}" =~ ^[Mm]ebibyte|^[Mm]i[Bb]s?$|^[Mm]$ ]]; then
+    value="$(echo "${value} * 1024^1" | bc -l)"
+    value="${value%.*}k"
+  elif [[ "${suffix}" =~ ^[Ki]ibibyte|^[Kk]i[Bb]s?$|^[Kk]$ ]]; then
+    value="${value}k"
+  else
+    value="${value}${suffix}"
+  fi
+
+  echo "${value}" # output in kibibytes
+}
+
+function subtract {
+  local input1="${1}"
+  local input2="${2}"
+
+  if [[ "${input1}" =~ P$ ]]; then
+    input1=${input1/P/}
+    input1=$(echo "${input1} * 1024^5" | bc -l)
+  elif [[ "${input1}" =~ T$ ]]; then
+    input1=${input1/T/}
+    input1=$(echo "${input1} * 1024^4" | bc -l)
+  elif [[ "${input1}" =~ G$ ]]; then
+    input1=${input1/G/}
+    input1=$(echo "${input1} * 1024^3" | bc -l)
+  elif [[ "${input1}" =~ M$ ]]; then
+    input1=${input1/M/}
+    input1=$(echo "${input1} * 1024^2" | bc -l)
+  elif [[ "${input1}" =~ k$ ]]; then
+    input1=${input1/k/}
+    input1=$(echo "${input1} * 1024" | bc -l)
+  # else
+  #   input1=$(echo "${input1}" | bc -l)
+  fi
+
+  if [[ "${input2}" =~ P$ ]]; then
+    input2=${input2/P/}
+    input2=$(echo "${input2} * 1024^5" | bc -l)
+  elif [[ "${input2}" =~ T$ ]]; then
+    input2=${input2/T/}
+    input2=$(echo "${input2} * 1024^4" | bc -l)
+  elif [[ "${input2}" =~ G$ ]]; then
+    input2=${input2/G/}
+    input2=$(echo "${input2} * 1024^3" | bc -l)
+  elif [[ "${input2}" =~ M$ ]]; then
+    input2=${input2/M/}
+    input2=$(echo "${input2} * 1024^2" | bc -l)
+  elif [[ "${input2}" =~ k$ ]]; then
+    input2=${input2/k/}
+    input2=$(echo "${input2} * 1024" | bc -l)
+  # else
+  #   input2=$(echo "${input2}" | bc -l)
+  fi
+
+  if [ "$(echo "${input1} >= ${input2}" | bc -l)" = 1 ]; then
+    output="$(echo "${input1} - ${input2}" | bc -l)"
+  else
+    echo "ERROR: not enough (remaining) space."
+    exit 3
+  fi
+  echo "${output%.*}"
+}
+
+function get_base2 {
+  local value="${1}"
+  local suffix=""
+  local exp=0
+
+  while [ "$(echo "1024^${exp} > ${value}" | bc)" = 0 ]; do
+    exp=$((exp + 1))
+  done
+  exp=$((exp - 1))
+  value="$(echo "${value} / 1024^${exp}" | bc)"
+
+  case "${exp}" in
+    1) suffix="KiB";;
+    2) suffix="MiB";;
+    3) suffix="GiB";;
+    4) suffix="TiB";;
+    5) suffix="PiB";;
+    6) echo "${exp} --- huh?" && exit 3;;
+  esac
+
+  echo "${value}${suffix}"
+}
+
+function get_base10 {
+  local value="${1}"
+  local suffix=""
+  local exp=0
+  while [ "$(echo "1000^${exp} > ${value}" | bc)" = 0 ]; do
+    exp=$((exp + 1))
+  done
+  exp=$((exp - 1))
+  value="$(echo "${value} / 1000^${exp}" | bc)"
+
+  case "${exp}" in
+    1) suffix="k";;
+    2) suffix="M";;
+    3) suffix="G";;
+    4) suffix="T";;
+    5) suffix="P";;
+    6) echo "${exp} --- huh?" && exit 3;;
+  esac
+
+  echo "${value}${suffix}"
 }
 
 declare -A PARTITIONS
 PARTITIONS=([root]="20G" [swap]="4G" [home]="fill" [share]="0G")
 function ask_partition_sizes {
-  show_header "Set partitiion sizes. (leave blank to use defaults)"
-  swap=$(ask_question "Swap (default: 4G)")
+  local free_size
+  local swap
+  local home
+  local root
+  local share
+
+  free_size="$(lsblk -b -dno SIZE "/dev/${DEVICE}")"
+
+  show_header "Specify partitiion sizes. $(get_base10 "${free_size}") ($(get_base2 "${free_size}")) available:"
+  swap=$(ask_question "Swap (default=4GiB):")
+  swap=$(sanitize_size_input "${swap}")
   if [[ -n "${swap}" ]]; then
     PARTITIONS["swap"]="${swap}"
+    free_size="$(subtract "${free_size}" "${swap}")"
+    show_info "$(get_base10 "${free_size}") ($(get_base2 "${free_size}")) available"
   fi
 
-  root=$(ask_question "Root (default: 20G)")
+  share=$(ask_question "Share (default=0GiB):")
+  share=$(sanitize_size_input "${share}")
+  if [[ -n "${share}" ]]; then
+    PARTITIONS["share"]="${share}"
+    if [[ "${share}" = "fill" ]]; then
+      free_size="0G"
+    else
+      free_size="$(subtract "${free_size}" "${share}")"
+      show_info "$(get_base10 "${free_size}") ($(get_base2 "${free_size}")) available"
+    fi
+  fi
+
+  root=$(ask_question "Root (default=20GiB):")
+  root=$(sanitize_size_input "${root}")
   if [[ -n "${root}" ]]; then
     PARTITIONS["root"]="${root}"
+    if [[ "${root}" = "fill" ]]; then
+      free_size="0G"
+    else
+      free_size="$(subtract "${free_size}" "${root}")"
+      show_info "$(get_base10 "${free_size}") ($(get_base2 "${free_size}")) available"
+    fi
   fi
 
   if [[ "${PARTITIONS["root"]}" != "fill" ]]; then
-    home=$(ask_question "Home (default: fill)")
+    home=$(ask_question "Home (default=fill):")
+    home=$(sanitize_size_input "${home}")
     if [[ -n "${home}" ]]; then
       PARTITIONS["home"]="${home}"
+      if [[ "${home}" = "fill" ]]; then
+        free_size="0G"
+      else
+        free_size="$(subtract "${free_size}" "${home}")"
+        show_info "$(get_base10 "${free_size}") ($(get_base2 "${free_size}")) available"
+      fi
     fi
   else
     PARTITIONS["home"]=0
-  fi
-
-  share=$(ask_question "Share: (default: 0G)")
-  if [[ -n "${share}" ]]; then
-    PARTITIONS["share"]="${share}"
   fi
 }
 
@@ -163,19 +343,22 @@ HOME_PARTITION=
 SWAP_PARTITION=
 SHARE_PARTITION=
 function set_partitions {
-  show_header "Setting up parititons on ${DEVICE}."
+  show_header "Writing parititons to ${DEVICE}..."
   sgdisk -Z "/dev/${DEVICE}"
-
   partprobe "/dev/${DEVICE}"
 
   local sgdisk_opts
+  local part_count
   sgdisk_opts="--clear"
   sgdisk_opts="${sgdisk_opts} --new=1:0:+1MiB --typecode=1:ef02"
-  sgdisk_opts="${sgdisk_opts} --new=2:0:+512MiB --typecode=2:ef00"
+  part_count=2
 
-  EFI_PARTITION="/dev/${DEVICE}2"
+  if [[ "${MAKE_EFI_PARTITION}" = "yes" ]]; then
+    sgdisk_opts="${sgdisk_opts} --new=2:0:+512MiB --typecode=${part_count}:ef00"
+    EFI_PARTITION="/dev/${DEVICE}${part_count}"
+    part_count=$(( part_count + 1 ))
+  fi
 
-  local part_count=3
   if is_size_nonzero "${PARTITIONS["share"]}"; then
     sgdisk_opts="${sgdisk_opts} --new=${part_count}:0:+${PARTITIONS["share"]} --typecode=${part_count}:8300"
     SHARE_PARTITION="/dev/${DEVICE}${part_count}"
@@ -303,7 +486,9 @@ function format_partitions {
     #   ;;
   esac
 
-  mkfs.vfat -F32 "${EFI_PARTITION}"
+  if [ -b "${EFI_PARTITION}" ]; then
+    mkfs.vfat -F32 "${EFI_PARTITION}"
+  fi
   if [ -e "${SWAP_PARTITION}" ]; then
     mkswap -L swap "${SWAP_PARTITION}"
     swapon "${SWAP_PARTITION}"
@@ -318,8 +503,10 @@ function format_partitions {
 
 function mount_install {
   mount "${ROOT_PARTITION}" /mnt
-  mkdir -p /mnt/boot/efi
-  mount "${EFI_PARTITION}" /mnt/boot/efi
+  if [ -b "${EFI_PARTITION}" ]; then
+    mkdir -p /mnt/efi
+    mount "${EFI_PARTITION}" /mnt/efi
+  fi
   if [ -e "${HOME_PARTITION}" ]; then
     mkdir -p /mnt/home
     mount "${HOME_PARTITION}" /mnt/home
